name: Playwright Tests

on:
  push:
    branches:
      - main  # Adjust to your main branch name
  pull_request:
    branches:
      - main  # Adjust to your main branch name
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.4.0'

      - name: Install dependencies
        run: npm install
        
      - name: Install playwright
        run: npx playwright install
        
      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Run Playwright tests with xvfb
        run: |
          xvfb-run npm run test
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: reports/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
