name: Playwright Tests

on:
  push:
    branches:
      - main  # Adjust to your main branch name
  pull_request:
    branches:
      - main  # Adjust to your main branch name
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.4.0'

      - name: Install dependencies
        run: npm install

      - name: Install playwright
        run: npx playwright install
        
      - name: Run Playwright-Cucumber tests
        run: npm run test
