name: Playwright Tests

on:
  push:
    branches:
      - main  # Adjust to your main branch name
  pull_request:
    branches:
      - main  # Adjust to your main branch name
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.4.0'

      - name: Install dependencies
        run: npm install
        
      - name: Install playwright
        run: npx playwright install
        
      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Run Playwright tests with xvfb
        run: |
          xvfb-run npm run test

      # - uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: my-reports
      #     path: |
      #       cucumber-report.html
      #       artifacts/
      #     retention-days: 30

        # Upload the report directory to the `gh-pages` branch
      - uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: cucumber-report.html  # Replace with the actual path

      - uses: actions/checkout@v3
        with:
          ref: gh-pages  # This will checkout the `gh-pages` branch

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: test-reports

      - name: Copy reports to publishing directory
        run: |
          mkdir -p published-reports
          cp -r test-reports/* published-reports/

      # Use a suitable action to deploy the report to your `gh-pages` branch
      - name: Deploy reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3  # Example action, replace with your preferred one
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./published-reports
          keep_files: true  # Keeps previously uploaded reports (optional)
